M7R0
I&_gradw,6#'%"vG_I'linalgG6$%*protectedG%(_syslibG%'vectorG6'%"PG%"kG%"sG%"mG%"
nG6"6"C%>8$-_F(%'matrixG6$""$F<?(8&"""F?F<%%trueG?(8(F?F?F<F@C%>&F76$F>FB-%%dif
fG6$*&&9$6#FBF?(%"hGFB!""(%"qGF>?(8'F?F?F<F@>FE,&FEF?*((((%&cristGFBFTF>F?&FL6#
FTF?(FOFTFPF?>FE*(FEF?(FOF>FPFNF?-%'RETURNG6#-%&evalmG6#F7F4F4F46#F?6+7&Q!F4FP"
"'"#87&FeoFP"#7"#D7&FeoFPFioFgo7&FeoFP"#<"#\7&FeoFP"#AF^p7&FeoFPF`p"#q7&FeoFP"#
E"#k7&FeoFPF`p"#X7&FeoFP"#6FdpF4,
I$divw,6#'%"MGF96&F.%"tGF0F26"F4C(>F7-F'6#F<>&F76#F?""!>&F76#""#Fiq>&F7FeqFiq?(
8%F?F?F<F@C$?(F>F?F?F<F@C$>&F76#Far,&FfrF?-FH6$*(&FL6$F>FarF?F[oFP(FOFarFPFQF??
(FTF?F?F<F@>Ffr,(FfrF?**(((FenFarF>FTF?&FL6$F>FTF?F[oFPFhnFPF?**(((FenF>F>FTF?&
FL6$FTFarF?FhnFPF^sFPF?>Ffr*&FfrF?F^sF?F_oF4F4F46#F?6.7&FeoFP""%"#57&FeoFP""*"#
?7&FeoFPFft"#;FhtFht7&FeoFPFftFip7&FeoFPFdt"#B7&FeoFP"#9"#`7&FeoFPF]p"#=7&FeoFP
"#@"#)*7&FeoFPF^u"#G7&FeoFPFdtF]pF4,
I%gRADw,6#'F&F'6&F^q%#v0G%"iG%"jG6"F4C'>Far-_F(%*transposeG6#-_F(%)multiplyG6$-
Fdv6#FL%%M_eEG>F7-F"Fgr>F7-F`o6#-%#&*G6$F7-Fdv6#F]w?(F>F?F?F<F@?(FTF?F?F<F@>&F7
Fgs-%)simplifyG6#F[x-F]oFaoF4FgwF46#F?6*7&FeoFP""(F]r7&FeoFPF?"#Y7&FeoFPF?F^u7&
FeoFPF?"#K7&FeoFPF?Ffo7&FeoFPF<F]r7&FeoFP""&"#I7&FeoFPF?FdtF4,
I4DeformationGradientw,F46%%#R'GF^vF_v6"F4C(>%#C_GF8>F7-Fdv6#-Fhv6$-Fdv6#%#RtGF
]w>Ffy-F"Fao>Ffy-F`o6#-Fdw6$FfyFfw?(FarF?F?F<F@?(F>F?F?F<F@>&Ffy6$FarF>-F]x6#-F
]x6#Fiz-F]o6#%#OkGF46#FfyF46#Fiq6+7&FeoFPFgtF<7&FeoFPF]rFit7&FeoFPF]rFex7&FeoFP
F]rF]p7&FeoFPF]r"#J7&FeoFPF]rF<7&FeoFPFctFep7&FeoFPFjo"#g7&FeoFPF]rFgoF4,
I3CauchyGreenMeasurew,F4F46"F4C%>%#G_GF8>Fe\l-Fhv6$Ffy-FdvFb[lF_[lF46$FfyFe\lF4
6#Fiq6&7&FeoFP"#>F<7&FeoFPF\yF^]l7&FeoFPF\y"#M7&FeoFPF\yFitF4,
I-SetPotentialw,6#%"aGF46"F4C%>%#_WGFL-%&printG6#%\o|[x|^u|[x|jv|\x|[s|\x|^s|[x
|^v|[x|cv|[x|dv~|[x|jv|[x|iv|\x|]s|[x|`v|[x|hv|\x|as|[x|cv|[x|[v|[x|fv~|[x|bv|[
x|[v|[x|_v|[x|[v|[x|hv~|[x|]v|\x|fs|\x|[s|[x|[v|[x|av|[x|`v|[x|hv|[x|cv|[x|`v|[
x|gvG-F\^l6#Fj]lF4F`^lF46#F?6&7&FeoFPFgoF]rFix7&FeoFPF?"#u7&FeoFPF?FftF4,
I.PiolaStressesw,F46/%$W_GG%#E_G%$I1GG%$I2GG%$I3GG%#d1G%#d2G%#d3GF^vF_v%$I1oG%$
I2oG%$I3oG6"F4C3>F7F8>%#D_GF8>Far-%&arrayG6%;F?F<F^`l%)identityG>F>-F`oFgr>FT-F
`o6#,&*&%#I1GF?FarF?F?Fe\lFP>FB-F`o6#*&%#I3GF?-_F(%(inverseG6#Fe\lF?>8)-FH6$Fj]
lFg`l>8*-FH6$Fj]l%#I2G>8+-FH6$Fj]lF\al@%33/FbalFiq/FfalFiq/F[blFiq-%&ERRORG6$%a
o|[x|ht|[x|`v|[x|]v|[x|`v|\x|[s|[x|hv|[x|iv|[x|`v~|[x|bv|[x|[v|[x|_v|[x|[v|[x|h
v|[x|cv|[x|`v~|\x|^s|[x|jv|\x|[s|\x|^s|[x|^v|[x|iv|[x|^v|[x|iv~|[x|jv|[x|iv|\x|
]s|[x|`v|[x|hv|\x|as|[x|cv|[x|[v|[x|fv|[x|[v!G%#W_G>F7-F`o6#,(*&FbalF?F>F?F?*&F
falF?FTF?F?*&F[blF?FBF?F?>8.-_F(%&traceGF`al>8/,&*$FbclF]r#F?F]r-Fccl6#-Fhv6$Fe
\lFe\l#FPF]r>80-_F(%$detGF`al?(8,F?F?F<F@?(8-F?F?F<F@>&F76$FedlFgdl-%%subsG6&/F
g`lFacl/FialFfcl/F\alF`dlFidl>Fi_l-F`o6#-Fdw6$,$F7F]rFfy@$/9#Fiq?(FedlF?F?F<F@?
(FgdlF?F?F<F@>&Fi_lFjdl-F]x6&F]fl%%sqrtG%%trigG%)symbolicGF_[lF46)Fj]lFg`lFialF
\alFfyFe\lFi_lF46#Fiq6;7&FeoFPF^uF<7&FeoFPF<Fau7&FeoFPF<F]p7&FeoFPF<Fj[l7&FeoFP
F<Fit7&FeoFPF<F`p7&FeoFPF<FfuFhflFhflFhfl7&FeoFPF<Fct7&FeoFPFip"#$*7&FeoFPFip"#
UFjfl7&FeoFPF<Fex7&FeoFPF<F^uF]gl7&FeoFPF\yFfo7&FeoFPFcx"#^F[glF]gl7&FeoFPFctF
\y7&FeoFPFfoFcx7&FeoFP"")"#cFcglF4,
I/CauchyStressesw,F4F46"F4C%>%#T_GF8>Fahl-F`o6#-F]x6#*&-Fdw6$Fi\lFi_lF?-FbdlFb[
lFPF_[lF46%FahlFi_lFfyF46#Fiq6&7&FeoFP"#:F<Fhfl7&FeoFPF<"#]FcglF4,
I8GetBoundaryValueProblemw,F46'%"AG%"SGF^v%#S1G%#S2G6"F4C)>F7Fdq>F7-Fjp6#-F`o6#
-Fdw6$Fi_lF]w>F7-Fhv6$F]wF7?(F>F?F?F<F@>&F76#F>-F]x6#FhjlF_o@'3/F[rFiq/F_rFiq>F
ar-%&solveG6$/FgqFiq-FH6%%#Q1G%#q1GFh[m330FgqFiq0F[rFiqF_[m>Far-Fb[m6$<$Fd[mF^[
m<$Fe[m-FH6%%#Q2GFh[mFh[m-%(WARNINGG6#%=Unusual~number~of~equations!G@%-%%typeG
6$Far%$setGC'>FT-F\el6$FarFe[m>FB-F\el6$FarFb\m>%.FirstEquationG-F\el6'/Fg[m-%#
P1G6#Fh[m/-FH6$Fj]mFh[m-%#P2GF\^m/Fd\m-%#P3GF\^m/-FH6$Fc^mFh[m-%#P4GF\^mFT>%/Se
condEquationG-F\el6'/-Fg[mF\^mFj]mF]^mFb^mFe^mFB-F]o6$/Fe[m-F]xFgn/Fb\m-F]xFMC$
>Ff]m-F\el6%Fi]mF]^mFar-F]o6#/Fe[m-F]xFgrF46&Fi_lFf]mF[_m%.ThirdEquationGF46#Fi
q657&FeoFP"#CF<Fcgl7&FeoFPF<Fjo7&FeoFPF<Fcu7&FeoFPF<"#Z7&FeoFPFc`m"#V7&FeoFPF<F
dt7&FeoFPF<Ffo7&FeoFPFdt"#T7&FeoFPF_il"#r7&FeoFPF_ilF_uF]gl7&FeoFPFftFa]lFaam7&
FeoFPFftFep7&FeoFPFft"#l7&FeoFPFft"#s7&FeoFPFio"#m7&FeoFPFioFgpF4,
I'GetBVPw,F4Fdil6"F4C'>F7Fdq>F7F]jl>F7Fdjl?(F>F?F?F<F@>FhjlFjjlF_oF4F^`mF46#Fiq
6)7&FeoFPFcxF<FcglFd`mFe`mFf`mFh`mFj`mF4,
I*Linearizew,6#'FeilF86%F^vF_v%)LinParamG6"F4C$@%/FielF?>F>%(epsilonG>F>&9"F\r?
(F7F?F?F<F@?(FarF?F?F<F@>&FL6$F7Far-F]x6#,&-F\el6$/FacmFiqFhcmF?*&FacmF?-F\el6$
F_dm-FH6$FhcmFacmF?F?F4F4F46#F?6)7&FeoFPFdtF]r7&FeoFPF?"#j7&FeoFPF^]l"#P7&FeoFP
FaglF^\lFixFjx7&FeoFPFct"#dF4
