M7R0
I,Coordinatesw,6$'%'coord1G%%nameG'%'coord2GF'6en%#r_G%$R_1G%$R_2G%$R_3G%$r_1G%
$r_2G%$r_3G%$e_1G%$e_2G%$e_3G%$E_1G%$E_2G%"lG%%g_11G%%g_12G%%g_13G%%g_21G%%g_22
G%%g_23G%%g_31G%%g_32G%%g_33G%$G11G%$G12G%$G13G%$G21G%$G22G%$G23G%$G31G%$G32G%$
G33G%%G_11G%%G_12G%%G_13G%%G_21G%%G_22G%%G_23G%%G_31G%%G_32G%%G_33G%#R_G%$E_3G%
$g11G%$g12G%$g13G%$g21G%$g22G%$g23G%$g31G%$g32G%$g33G%"iG%"jG%"kG%"SG%%NdimG%.s
implify/combG6"6"C9@)/9$.%,CylindricalGC(>%#x1G*&%"rG"""-%$cosG6#%$phiGF[p>%#x2
G*&FjoF[p-%$sinGF^pF[p>%#x3G%"zG>%#q1GFjo>%#q2GF_p>%#q3GFgp/Fco.%*SphericalGC(>
Fho*(FjoF[p-F]p6#%&thetaGF[pF\pF[p>Fap*(FjoF[pFdqF[pFcpF[p>Ffp*&FjoF[p-FdpFeqF[
p>FipFjo>F[qF_p>F]qFfq/Fco.%*CartesianGC(>Fho%"xG>Fap%"yG>FfpFgp>FipFdr>F[qFfr>
F]qFgp-%&ERRORG6#%inOnly~Cartesian,~Cylindrical~and~Spherical~coordinates~allow
ed.G@)/9%FdoC)>%#X1G*&%"RGF[p-F]p6#%$PhiGF[p>%#X2G*&FfsF[p-FdpFhsF[p>%#X3G%"ZG>
%#Q1GFfs>%#Q2GFis>%#Q3GF`t>%#RtG-_I'linalgG6$%*protectedG%(_syslibG%'vectorG6$"
"$7%Ffs""!F`t/FasF_qC)>Fds*(FfsF[p-F]p6#%&ThetaGF[pFgsF[p>F[t*(FfsF[pFhuF[pF]tF
[p>F_t*&FfsF[p-FdpFiuF[p>FbtFfs>FdtFis>FftFju>Fht-Fjt6$Fau7%FfsFcuFcu/FasF`rC)>
Fds%"XG>F[t%"YG>F_tF`t>FbtFjv>FdtF\w>FftF`t>Fht-Fjt6$Fau7%FjvF\wF`tF[s>8L-Fjt6#
Fau?(8WF[pF[pFau%%trueG>&Ffw6#Fjw(FjvFjw>8$Fgw?(FjwF[pF[pFauF[x>&FaxF^x(FdrFjw?
(FjwF[pF[pFauF[xC%>(FfwFjwFgw>(FaxFjwFgw?(8XF[pF[pFauF[xC$>&Fix6#F]y-%%diffG6$&
FfwFay(%"QGFjw>&F[yFay-Fcy6$&FaxFay(%"qGFjw>%#h1G.F`z>%#h2G.Fcz>%#h3G.Ffz>%#H1G
.Fiz>%#H2G.F\[l>%#H3G.F_[l?(FjwF[pF[pFauF[xC&-%'assumeG6#2Fcu(%"hGFjw-Fd[l6#2Fc
u(%"HGFjw>F\\l-%)simplifyG6%-F`\l6$-%%sqrtG6#-_F[u%(dotprodG6%FixFix.%+orthogon
alG%%trigGFe\l%)symbolicG>Fg[l-F`\l6%-F`\l6$-Fe\l6#-Fh\l6%F[yF[yF[]lF]]lFe\lF^]
l?(FjwF[pF[pFauF[xC%>(%#E_GFjwFgw>(%#e_GFjwFgw?(F]yF[pF[pFauF[xC$>&F[^lFay*&F`y
F[pF\\l!"">&F^^lFay*&FiyF[pFg[lFe^l>8fnw,6#%%exprGF_o6"F_o-%'RETURNG6#-%(combin
eG6$FcoF]]lF_oF_oF_o6#F[p6$7&Q!F_oFe^l"#A"#D7&Fh_lFe^l"#F"#_>%%M_eEG-_F[u%'matr
ixG6$FauFau?(8ZF[pF[pFauF[x?(8YF[pF[pFauF[x>&F_`l6$Fe`lFg`l-F`\l6$-_F[u%)multip
lyG6$-_F[u%*transposeG6#(F\^lFe`l(F_^lFg`l%%combG?(FjwF[pF[pFauF[x?(F]yF[pF[pFa
uF[x@%/FjwF]yC$>((%"gGFjwF]y*$Fg[l""#>((%#g_GFjwF]y*$F^blFe^lC$>F^blFcu>FdblFcu
?(80F[pF[pFauF[x?(FjwF[pF[pFauF[x?(F]yF[pF[pFauF[xC%>(((%&cristGF\clFjwF]yFcu?(
Fg`lF[pF[pFauF[x>Facl,*FaclF[p*&((FfblFg`lF\clF[p-Fcy6$((F`blFg`lF]yF]zF[pF[p*&
FiclF[p-Fcy6$(F_blFg`l(F^zF]yF[pF[p*&FiclF[p-Fcy6$F^bl(F^zFg`lF[pFe^l>Facl,$Fac
l#F[pFbbl?(FjwF[pF[pFauF[x?(F]yF[pF[pFauF[x@%F[blC$>((%"GGFjwF]y*$F\\lFbbl>((%#
G_GFjwF]y*$F`elFe^lC$>F`elFcu>FeelFcu?(F\clF[pF[pFauF[x?(FjwF[pF[pFauF[x?(F]yF[
pF[pFauF[xC%>(((%&CristGF\clFjwF]yFcu?(Fg`lF[pF[pFauF[x>Fafl,*FaflF[p*&((FgelFg
`lF\clF[p-Fcy6$((FbelFg`lF]yFfyF[pF[p*&FiflF[p-Fcy6$(FaelFg`l(FgyF]yF[pF[p*&Fif
lF[p-Fcy6$F`el(FgyFg`lF[pFe^l>Fafl,$FaflFjdl-F`_l6#%#OkGF_o6bpFdsF[tF_tFhoFapFf
pFbtFdtFftFipF[qF]qFhtF_`lFizF\[lF_[lF`zFczFfz%)crist121G%)crist122G%)crist123G
%)crist131G%)crist132G%)crist133G%)crist111G%)crist112G%)crist113G%)crist211G%)
crist212G%)crist213G%)crist221G%)crist222G%)crist223G%)crist231G%)crist232G%)cr
ist233G%)crist321G%)crist322G%)crist323G%)crist331G%)crist332G%)crist333G%)cris
t311G%)crist312G%)crist313G%)Crist121G%)Crist122G%)Crist123G%)Crist131G%)Crist1
32G%)Crist133G%)Crist111G%)Crist112G%)Crist113G%)Crist211G%)Crist212G%)Crist213
G%)Crist221G%)Crist222G%)Crist223G%)Crist231G%)Crist232G%)Crist233G%)Crist321G%
)Crist322G%)Crist323G%)Crist331G%)Crist332G%)Crist333G%)Crist311G%)Crist312G%)C
rist313GFjvF\wF`tFdrFfrFgpFfsFisFjoF_pFjuFfqF_o6#Fbbl6gq7&Fh_lFe^l"#7Fbbl7&Fh_l
Fe^lFe^l""%7&Fh_lFe^l""("#?Fj[m7&Fh_lFe^lF[\mFg[mF]\m7&Fh_lFe^lF[\m"#9F]\m7&Fh_
lFe^l"#5"#MF`\m7&Fh_lFe^lFa\mFj_l7&Fh_lFe^lFa\m"#:7&Fh_lFe^lFa\m"#<7&Fh_lFe^lFa
\m"#>7&Fh_lFe^lFe\mF\\mFj\mFj\mFj\mFj\mFj\m7&Fh_lFe^l"#="#))7&Fh_lFe^lFe^lFcu7&
Fh_lFe^lFi[mFg\mF_]m7&Fh_lFe^lFi[m""*F`]m7&Fh_lFe^lFi[m"#6F`]m7&Fh_lFe^lFi[m"#C
7&Fh_lFe^lFa]m"#LFf]m7&Fh_lFe^lFa]mFe]m7&Fh_lFe^lFa]mF_\m7&Fh_lFe^lFa]m"#;7&Fh_
lFe^lFa]mF\]m7&Fh_lFe^lFa]m"#H7&Fh_lFe^l"#8F\]mF_^mF_^mF_^mF_^mF_^m7&Fh_lFe^lF`
^mFg]m7&Fh_lFe^lF[^m"#')7&Fh_lFe^lFauFe\m7&Fh_lFe^lFi[mF\\m7&Fh_lFe^l""'F[^m7&F
h_lFe^lFg^mF\]m7&Fh_lFe^lF[\mFe]m7&Fh_lFe^lFa\mF\\m7&Fh_lFe^lFi[mFg^mFc\m7&Fh_l
Fe^lF`^m"#G7&Fh_lFe^lF[\mFa\m7&Fh_lFe^lFg[m"#P7&Fh_lFe^lFe\m"#S7&Fh_lFe^lFauFa
\m7&Fh_lFe^lFg[mFi\m7&Fh_lFe^l"#@F]_mFc_mFd_mFe_m7&Fh_lFe^lFauFg^m7&Fh_lFe^l"")
Ff_m7&Fh_lFe^l"#B"#O7&Fh_lFe^lFi_m"#&)F]`m7&Fh_lFe^l""&Fg^mFc\m7&Fh_lFe^lFi_mF[
`m7&Fh_lFe^lFi_mFa]m7&Fh_lFe^lFg[mFb\m7&Fh_lFe^lF_\mF\`m7&Fh_lFe^lF``mFj_l7&Fh_
lFe^lF``mFf_m7&Fh_lFe^lF``m"#r7&Fh_lFe^lFg^m"#o7&Fh_lFe^lFg^m"#j7&Fh_lFe^lFi[mF
e\m7&Fh_lFe^lF``mFg[m7&Fh_lFe^lF[\m"#Q7&Fh_lFe^lFi\mFb\m7&Fh_lFe^l"#N"#`7&Fh_lF
e^lFg[mFi_l7&Fh_lFe^lFe]mFcam7&Fh_lFe^lFi[mF``m7&Fh_lFe^lF``mF[\mFb`m7&Fh_lFe^l
Fc]mF]_m7&Fh_lFe^lFc]m"#e7&Fh_lFe^lF`^m"#a7&Fh_lFe^lFc]m"#VF]amF^amF_amFaamFbam
FeamFfamFgamFhamFb`mFiamFjamF\bmF^bm7&Fh_lFe^lFe^lFa\mF_o
